### ISSUE TITLE
TrueOS-Desktop-2016-08-31-x64-USB.img black/blank screen instead of TrueOS Installation Menu

### ISSUE THREAD

**Issue by madewo** [trueos/trueos-desktop#3]
TUXEDO InfinityBook
Intel Core-i Prozessor, Skylake: Intel Core i7-6500U: 2x 2.5-3.1GHz Dual-Core, 4 Threads, 4MB Cache
Intel HD Graphics 520

When booting from USB I get the used FreeBSD start messages until something like
Intel graphics detected
Using Intel video driver
and some (about 8) drm messages with an drm error
(that I can't read because of the blackend screen)
After that nothing happens, but the system (freebsd) seams to run, at least it is possible to shutdown it regulary by pressing the power-button for a second.

I guess there is a problem with the intel-video-driver so I tried the 'Failsave VESA-mode', unfortunately with the same result.
I was able to install PCBSD11.0-CURRENTJUNE2016-06-10-2016-x64-USB.img in SCFB-Mode, but wasn't able to start the installed system afterwards (xorg is trying to start (a lot of 'Please wait ... Starting xorg' messages for some time) but ends up in a black screen too).

I would be glad to help with further information, please let me know how to attain these if needed.

Kind regards
Martin

**Comment by pkgdemon** [comment]
It sounds like you are not getting to the installation menu due to the i915kms loading when the video detection routine runs ahead of the installer menu.  I resolved this for the next image which should come out sometime later this week.  It will not load i915kms until the either auto detect, or intel is selected.  This will allow use of VESA, or SCFB on unsupported graphics cards.

Especically since you have skylake I would report the drm errors here where that is being developed specifically for further investigation:

https://github.com/FreeBSDDesktop/freebsd-base-graphics/issues
